nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ["*"]
        allow_headers: ["*"]
        allow_methods: ["POST", "PUT", "GET", "DELETE", "OPTIONS"]
        expose_headers: ["Content-Type', 'Authorization"]
        max_age: 3600
    paths:
        "^/":
            allow_origin: ["*"]
            allow_headers: ["*"]
            allow_methods: ["POST", "PUT", "GET", "DELETE", "OPTIONS"]
            expose_headers: ["Content-Type', 'Authorization"]
            max_age: 3600
